//! Layer A: one typed table row per decoded event.
//!
//! This is the faithful layer. It takes a [`Decoded`] record and produces the row a
//! table generated from that event's ABI would hold: every argument as a column,
//! under its ABI name, plus the identity columns every store needs.
//!
//! It is deliberately *not* semantic. It knows nothing about Uniswap or what
//! `amount0` means; it only knows the ABI's own shape. That is what lets it work for
//! any event in any ABI without a per-protocol extractor — and it is why it is the
//! first layer rather than the last. Layer B
//! ([`crate::trades`]) is where protocol meaning lives.
//!
//! # Column set
//!
//! Every table gets the same identity columns, then the event's own arguments:
//!
//! | Column | Source |
//! | --- | --- |
//! | `block_number`, `block_timestamp`, `block_hash` | the decoded record |
//! | `transaction_hash`, `log_index` | the raw log's natural key |
//! | `contract_address` | [`Decoded::address`] |
//! | `event_name`, `signature`, `selector` | the ABI's event |
//! | *the event's arguments* | [`Decoded::indexed`] then [`Decoded::body`], by name |
//!
//! `indexed` comes before `body` so the column order is stable for a given ABI
//! rather than depending on how the decoder happened to split them.

use alloy_primitives::{Address, B256};
use wire::envelope::Decoded;

use crate::column::Column;

/// One decoded event as a row of typed columns.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EventRow {
    /// The table this row belongs to, which is the event's name.
    ///
    /// A store that generates one table per event uses this to pick it. It is the
    /// event name rather than a table name because naming is the store's business.
    pub table: String,
    /// The event's arguments, in ABI order, indexed first.
    pub columns: Vec<Column>,
    /// The row's identity, which is also its dedupe key.
    pub identity: Identity,
}

/// The identity columns every generated table carries.
///
/// These are what a consumer joins, filters, and orders on, so they are lifted out
/// of the argument list rather than left to be found among the ABI's parameters.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Identity {
    /// Height of the block containing the event.
    pub block_number: u64,
    /// Timestamp of that block.
    pub block_timestamp: u64,
    /// Hash of that block.
    pub block_hash: B256,
    /// The contract that emitted the event.
    pub contract_address: Address,
    /// The log's position in its block, paired with the transaction below.
    pub log_index: u64,
}

impl EventRow {
    /// Builds the row for a decoded event.
    #[must_use]
    pub fn from_decoded(decoded: &Decoded) -> Self {
        // Indexed first, then body, so the column order is a property of the ABI
        // rather than of how the decoder split its arguments.
        let columns = decoded
            .indexed
            .iter()
            .chain(&decoded.body)
            .map(|arg| Column::from_arg(&arg.name, &arg.value))
            .collect();

        Self {
            table: decoded.name.clone(),
            columns,
            identity: Identity {
                block_number: decoded.block_number,
                block_timestamp: decoded.block_timestamp,
                block_hash: decoded.block_hash,
                contract_address: decoded.address,
                log_index: log_index(&decoded.source),
            },
        }
    }

    /// The column for `name`, if this event declares one.
    ///
    /// This is the accessor layer B uses, and the reason the arguments carry names:
    /// an extractor asks for `amount0` and fails loudly when the ABI does not declare
    /// it, rather than indexing a position that a new ABI revision could move.
    #[must_use]
    pub fn column(&self, name: &str) -> Option<&Column> {
        self.columns.iter().find(|column| column.name == name)
    }
}

/// The log index out of a raw log's `block:transaction:log_index` key.
///
/// The decoded record carries its source as a key rather than as fields, so the
/// position is parsed back out of it. A key that does not parse yields zero rather
/// than failing, because the key is generated by this workspace and a malformed one
/// is a bug rather than bad input.
fn log_index(source: &str) -> u64 {
    source
        .rsplit_once(':')
        .and_then(|(_, index)| index.parse().ok())
        .unwrap_or_default()
}

#[cfg(test)]
// The crate denies `expect`/`unwrap` to keep production paths honest; tests are
// allowed them per the repository test style, since a failed expectation there
// means the fixture or setup is wrong.
#[expect(clippy::expect_used)]
mod tests {
    use alloy_primitives::{Address, B256, U256};
    use wire::envelope::{Decoded, DecodedArg};
    use wire::typed::TypedValue;

    use super::EventRow;
    use crate::column::Value;

    fn decoded() -> Decoded {
        Decoded {
            name: "Swap".to_owned(),
            address: Address::from([0xd0; 20]),
            selector: B256::from([0xc4; 32]),
            signature: "Swap(address,address,int256,int256,uint160,uint128,int24)".to_owned(),
            source: format!("51913794:{}:767", B256::from([0x2a; 32])),
            indexed: vec![
                DecodedArg {
                    name: "sender".to_owned(),
                    value: TypedValue::Address {
                        value: Address::from([0x6f; 20]),
                    },
                },
                DecodedArg {
                    name: "recipient".to_owned(),
                    value: TypedValue::Address {
                        value: Address::from([0x6f; 20]),
                    },
                },
            ],
            body: vec![
                DecodedArg {
                    name: "amount0".to_owned(),
                    value: TypedValue::Int {
                        value: alloy_primitives::I256::try_from(-3_180_585_820_646_654_i64)
                            .expect("fits"),
                        bits: 256,
                    },
                },
                DecodedArg {
                    name: "amount1".to_owned(),
                    value: TypedValue::Int {
                        value: alloy_primitives::I256::try_from(8_586_564_i64).expect("fits"),
                        bits: 256,
                    },
                },
                DecodedArg {
                    name: "sqrtPriceX96".to_owned(),
                    value: TypedValue::Uint {
                        value: U256::from(1_u128 << 100),
                        bits: 160,
                    },
                },
            ],
            block_number: 51_913_794,
            block_hash: B256::from([0xd4; 32]),
            block_timestamp: 1_700_000_000,
        }
    }

    /// The row carries the ABI's arguments in order, indexed before body, so a
    /// generated table's column order is stable for a given ABI.
    #[test]
    fn arguments_become_columns_in_abi_order() {
        let row = EventRow::from_decoded(&decoded());
        let names: Vec<&str> = row.columns.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(
            names,
            ["sender", "recipient", "amount0", "amount1", "sqrtPriceX96"]
        );
        assert_eq!(row.table, "Swap");
    }

    /// Looking a column up by name is what layer B does, and it is what the names
    /// exist for.
    #[test]
    fn a_column_is_addressable_by_its_abi_name() {
        let row = EventRow::from_decoded(&decoded());
        let amount0 = row.column("amount0").expect("the ABI declares amount0");
        assert_eq!(amount0.value, Value::Integer(-3_180_585_820_646_654));
        assert!(row.column("amount2").is_none());
    }

    /// Identity is lifted out of the argument list rather than left among the ABI's
    /// parameters, and the log position is recovered from the source key.
    #[test]
    fn identity_is_lifted_from_the_record() {
        let row = EventRow::from_decoded(&decoded());
        assert_eq!(row.identity.block_number, 51_913_794);
        assert_eq!(row.identity.block_timestamp, 1_700_000_000);
        assert_eq!(row.identity.contract_address, Address::from([0xd0; 20]));
        assert_eq!(row.identity.log_index, 767);
    }

    /// A wide argument stays exact in the row rather than being rounded into a
    /// column that cannot hold it.
    #[test]
    fn a_wide_argument_stays_exact() {
        let row = EventRow::from_decoded(&decoded());
        let price = row.column("sqrtPriceX96").expect("the ABI declares it");
        assert_eq!(
            price.value,
            Value::Decimal((U256::from(1_u128 << 100)).to_string())
        );
    }
}
